### ISSUE TITLE
I am appalled at the lack of AM2R on this list

### ISSUE THREAD

**Issue by Welding-Torch** [radek-sprta/awesome-game-remakes#2]
AM2R is a platformer based on the game Metroid II. It was released in 2016 by Miltion Guasti and is one of the best games that I have ever played. For more information visit [www.reddit.com/r/AM2R](url)

**Comment by radek-sprta** [comment]
Thank you for the suggestion. I have checked the subreddit and the closest thing to canonical repository seems to be https://github.com/Lojemiru/AM2R-Community-Updates. However, judging by the license, it is not an open-source project.
