### ISSUE TITLE
What do you think about moving this list to Wikipedia?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [radek-sprta/awesome-game-remakes#28]
Because now it depends on your account, when on Wikipedia people will be able to maintain it thousands of years.

And on Wikipedia we will see - blue link - article about a game exists, red link - not exists.

**Comment by radek-sprta** [comment]
Hello Vitaly. Personally, I don't find the Wikipedia interface pleasant to work with, so I do not contribute there.
But you're more than welcome to put the list on Wiki.

**Comment by vitaly-zdanevich** [comment]
> I don't find the Wikipedia interface pleasant to work with

You can work with Wikipedia using git :)

**Comment by radek-sprta** [comment]
That's news to me, thanks.
I will check it out in that case.

-------- オリジナルメッセージ --------
2024/10/27 22:20、Vitaly Zdanevich  書きました：
