### ISSUE TITLE
Mark Software that does not require non-free data?

### ISSUE THREAD

**Issue by kwadroke** [radek-sprta/awesome-game-remakes#8]
Being that most of the games require non-free data from original games (or via Steam/GOG), it might be advantageous to disclaim that non-free data is needed to play for most games.

Maybe put an Asterisk or some sort of marker for those games that does not need non-free game data like Taisei or are Free game data like Free-Doom.

**Comment by radek-sprta** [comment]
That's a great suggestion. Once I have a bit more time, I'll go through the list and double check which games do not need original assets.

**Comment by radek-sprta** [comment]
Addressed in [5597869](https://github.com/radek-sprta/awesome-game-remakes/commit/5597869072a62d4fa6dd0cd1f971612b2847e621).
